name: CI-CD & Docker-compose

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Compose-Up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # GHCR에 로그인
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CICD_TOKEN }}

      # Docker Compose 실행
      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d --build

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-go]
    steps:
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/github-actions-auto
            git pull
            if docker-compose ps | grep -q "Up"; then
              docker-compose down
            fi
            docker-compose up -d --build