name: CI-CD & Docker-compose

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Compose-Up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # GHCR에 로그인
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker Compose 실행
      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d --build

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-go]
    steps:
      # SSH를 사용하여 EC2 인스턴스에 배포
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo /usr/sbin/groupadd -f docker
            sudo /usr/sbin/usermod -aG docker $USER
            sudo chown root:docker /var/run/docker.sock
            cd /github-actions-auto
            git pull
            docker-compose down
            docker-compose up -d --build
