name : CI-CD & Docker-compose 

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Compose-Up 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        
      - name: Build and Run Docker Compose 
        run: |
          docker-compose up -d --build

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-go]
    steps:
      - name: SSH and Deploy to EC2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /github-actions-auto
            git pull 
            docker-compose down 
            docker-compose up -d --build
